sonar.projectKey=BryanROGER_eni
sonar.organization=bryanroger
sonar.sources=.
sonar.host.url=https://sonarcloud.io

# Chemins vers les sources
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/venv/**, **/.venv/**, **/tests/**
